def _getFieldNameList():
    return [
        'supplier',
        'checkIn',
        'nights',
        'pos',
        'city',
        'hotel_id',
        'adults',
        'hotel_name',
        'latitude',
        'longitude',
        'board',
        'currency',
        'star_rating',
        'pathPage',
        'promotion',
        'promotion_desc',
        'direct_Payment',
        'multiple_zone_check',
        'room_type',
        'hotel_location',
        'total_price',
    ]

